export const GET_SERVICES_REQUEST = 'GET_SERVICES_REQUEST';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SET_FEEDBACK_INACTIVE = 'SET_FEEDBACK_INACTIVE';
