export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';

export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

export const GET_SHOPPINGCARTS_REQUEST = 'GET_SHOPPINGCARTS_REQUEST';
export const GET_SHOPPINGCARTS_SUCCESS = 'GET_SHOPPINGCARTS_SUCCESS';
export const GET_SHOPPINGCARTS_FAILURE = 'GET_SHOPPINGCARTS_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const SET_FEEDBACK_INACTIVE = 'SET_FEEDBACK_INACTIVE';
